### ISSUE TITLE
Advancement progress doesn't update in realtime

### ISSUE THREAD

**Issue by Lauriichan** [MarkusBordihn/BOs-Advancements-Tracker#10]
**Describe the bug**
Advancement progress doesn't update in realtime if criteria is completed

**To Reproduce**
1. Go into the tracker menu of this mod
2. Track the biomes o' plenty advancement
3. Run in any biome you didn't were in yet
4. See that the advancement does update in the normal minecraft advancements tab but not for this mod

**Expected behavior**
I expect that if I complete a criteria the progress of the advancement is being updated

**Additional context**
I was testing this with the "Wanderer" advancement of Biomes o' plenty
while playing the [Valhelsia 3](https://www.curseforge.com/minecraft/modpacks/valhelsia-3) modpack.
It doesn't contain this mod by default, I manually installed it

**Comment by MarkusBordihn** [comment]
Thanks for the report. I performed some test with the current beta version for 1.18.2 on this.
It's seems that the advancements event is not update in some cases, even it should.

I checked Biomes o' plenty and they using the standard advancements so it seems like an issue like specific advancements updates are handled.

Will provide an update as soon this is fixed.

**Comment by Lauriichan** [comment]
Okay thanks for the response!

**Comment by MarkusBordihn** [comment]
Ok, was able to find the error and to add a fix for this.
Basically as soon you open any "normal" or "modded" advancement  screen, the advancement update events get's overwritten with "null".
