### ISSUE TITLE
HUD UI not changing alongside config changes. [1.18.2] FORGE

### ISSUE THREAD

**Issue by Zeekicus** [MarkusBordihn/BOs-Advancements-Tracker#11]
Every time I want to move the HUD widget it doesn't: nor does it resize.
I have used Mod Config menu / configues
I have also tried going through create config
and finally I even went to the config file itself. Got nothing still won't adjust.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. The beta currently includes hard-coded values, I will fix this in the next update together with a proper documentation.

**Comment by MarkusBordihn** [comment]
This is fixed with version https://www.curseforge.com/minecraft/mc-mods/advancements-tracker/files/3855733
Which allows to position the widget on a pre-defined definition and to move it from there with top and left values.
