### ISSUE TITLE
1.19 crash multimc

### ISSUE THREAD

**Issue by Dartsgame974** [MarkusBordihn/BOs-Advancements-Tracker#14]
Hello install the in 1.19 on MultiMc Launcher but Minecraft wont launch and crashed.
[latest.log](https://github.com/MarkusBordihn/BOs-Advancements-Tracker/files/9128787/latest.log)

**Comment by MarkusBordihn** [comment]
Please post the corresponding crashlog.
At the moment it looks like a OptiFine issue.
