### ISSUE TITLE
Fabric 1.19 View other players' achievements, top players by achievements, titles.

### ISSUE THREAD

**Issue by MrJorman** [MarkusBordihn/BOs-Advancements-Tracker#15]
View other players' achievements, top players by achievements, titles.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback, but it seems you mixed up the mod with something else.

1. First of all there is no "Fabric" version of this mod as far as I know ? 🤔
2. This is a pure client side mod, so it has no access to any server data like other players achievements, top players by achievements or something like this. For this you would need a additional server side mod instead.

I will close this request, but will check if this is something which could be easily offered as an additional mod or so.
