### ISSUE TITLE
[1.19.2] Rendering fonts, causing a huge FPS drop.

### ISSUE THREAD

**Issue by MooZonkey** [MarkusBordihn/BOs-Advancements-Tracker#16]
There is a bug or similar critical issue with this mod. It tanks FPS to low double digits on my desktop, my laptop, and one of my friends computers. Both of my computers were getting 15-40FPS, and my friends computer was getting 12FPS. 

To reproduce this issue I just need to have the default advancement tracker GUI open. 
The moment I press alt+L to close it, my FPS skyrockets from ~30FPS to 80+ FPS.
Opening said menu back up causes the FPS to tank again. This is reproducible 100% of the time.  

https://user-images.githubusercontent.com/23399643/189463114-b62b49dd-554f-4dc4-9ae4-169a0be08bcb.mp4

**Comment by MooZonkey** [comment]
If it helps with troubleshooting, the current mod pack I am running is called "Friends United".

**Comment by MarkusBordihn** [comment]
Thanks for the report. Unfortunately I'm not really able to reproduce the issue on my side, see:
![image](https://user-images.githubusercontent.com/12183293/189494416-41a4b4b0-f797-4684-8e5b-82a61e830c0c.png)

The renderOverlay only takes about 1% of the total CPU time, which should only influence at least 1-5 fps and not 50fps like in your video.

**Without overlay:**
![image](https://user-images.githubusercontent.com/12183293/189494528-095f4e02-553b-4df6-99a2-2fdd89bee8fc.png)

**With overlay:**
![image](https://user-images.githubusercontent.com/12183293/189494567-15f140b3-fad5-421c-a7cc-29d02dc582ac.png)

Could you let me know if you are using any alternative render engine like a shader, shader pack, optifine or anything which adjust your UI, fonts or something like this ?

If you are using any kind of shaders or alternative render engine it could be that the semi-transparent backgroud is causing performance issues. But happy to take a closer look.

Are you getting the same frame drop if you are just looking down / or looking at a wall and opening the screen ?

**Comment by MooZonkey** [comment]
I am not using any third party rendering engine or game client aside from forge. I am not running shaders ,or optifine, or anything else like that. The only thing that I changed when it comes to UI is the UI scale. Keeping the UI scale at default doesn't change the issue. I get the same drops no matter what biome or direction I look in. Opening the settings menu gives me more FPS back, but if the advancement tracker UI is active then my FPS immediately tanks again after closing the settings menu. 

I have also noticed that it doesn't matter what my graphics settings are. They could be minimal settings or maxed out and I still get this issue with the advancement tracker eating my FPS.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. I was able to reproduce the issue with the mod pack https://www.curseforge.com/minecraft/modpacks/friends-united and isolate the issue down to the font renderer.

![image](https://user-images.githubusercontent.com/12183293/189532140-52f15d22-3799-4798-960c-5f27f1b56112.png)

I will check if there is anything in the mod pack which influence the font renderer and will additional add additional caching to avoid such issue in the feature.

**Comment by MooZonkey** [comment]
Very interesting. Thank you for the help.

**Comment by MarkusBordihn** [comment]
The issue should be fixed with:
https://www.curseforge.com/minecraft/mc-mods/advancements-tracker/files/3984521

The mod only need about 2.41% of the render thread , see:
https://spark.lucko.me/aVmOugQovE?hl=1285

I will add additional performance improvement over the next weeks.
