### ISSUE TITLE
Some GUI strings are not translatable

### ISSUE THREAD

**Issue by Regnander** [MarkusBordihn/BOs-Advancements-Tracker#20]
**Describe the bug**
While translating this mod to my native tongue, I found some hardcoded strings not available for translation:
* "Criteria:" https://github.com/MarkusBordihn/BOs-Advancements-Tracker/blob/5d1b7b938e929ef9cd739cf220df6584d0636d03/src/main/java/de/markusbordihn/advancementstracker/client/gui/screens/AdvancementDetailScreen.java#L81
* "Rewards:" https://github.com/MarkusBordihn/BOs-Advancements-Tracker/blob/5d1b7b938e929ef9cd739cf220df6584d0636d03/src/main/java/de/markusbordihn/advancementstracker/client/gui/screens/AdvancementDetailScreen.java#L99
* "exp" https://github.com/MarkusBordihn/BOs-Advancements-Tracker/blob/5d1b7b938e929ef9cd739cf220df6584d0636d03/src/main/java/de/markusbordihn/advancementstracker/client/gui/screens/AdvancementDetailScreen.java#L102

**To Reproduce**
1. Go to https://github.com/MarkusBordihn/BOs-Advancements-Tracker/blob/1.19.3/src/main/resources/assets/advancements_tracker/lang/en_us.json
2. Search for "Criteria", "Rewards" or "exp"
3. No results are found since they yet to be added.

**Expected behavior**
I expected the mentioned strings to be translatable.

**Screenshots**
![2023-07-16_17 48 44(1)](https://github.com/MarkusBordihn/BOs-Advancements-Tracker/assets/17113053/ade590d0-2037-40c6-bb39-1cbeb8303409)
_Some untranslatable strings marked with pink outline._

**Debugging**
–

**Additional context**
–

**Comment by MarkusBordihn** [comment]
Thanks for the report. I will replace the hard-coded strings to translatable string with the next update which will also include your translation file.
