### ISSUE TITLE
[1.20.1] Crash

### ISSUE THREAD

**Issue by emihead** [MarkusBordihn/BOs-Advancements-Tracker#21]
**Describe the bug**
Crash when I opened a ruined portal chest. Possibly some kind of incompatibility.

**To Reproduce**
1. Open ruined portal chest

**Expected behavior**
Game doesn't crash

**Debugging**
[Log](https://mclo.gs/7TVXdK1#L7784)

**Comment by emihead** [comment]
Link sends you to the wrong line, oops. [Here's](https://mclo.gs/7TVXdK1#L7784) the actual crash

**Comment by MarkusBordihn** [comment]
Unable to reproduce in the latest version, please open a new bug if this still happen with version 6.1.x
