### ISSUE TITLE
[Suggestion / "Fix"] Limit category text descriptions to a character limit, require mouseover tooltip when text is cut off.

### ISSUE THREAD

**Issue by PlayfulPiano** [MarkusBordihn/BOs-Advancements-Tracker#23]
Currently if there are categories with text descriptions that are too long, they are rendered on top of other categories, making it severely illegible.

Adding a character limit, where you can see the full description via mouseover tooltip, would fix this issue.
![image](https://github.com/MarkusBordihn/BOs-Advancements-Tracker/assets/3158887/3829aa62-9083-450e-911f-df9a059f6077)

**Comment by MarkusBordihn** [comment]
With version 6.1.0 the title has a line limit of 1 and a line limit of 2 for the description.

<img width="151" alt="image" src="https://github.com/MarkusBordihn/BOs-Advancements-Tracker/assets/12183293/9107e546-ebe4-4161-b479-5db0cc64397d">
